package de.unisaarland.cs.se.selab.config

const val VILLAGE = "village"
const val ROAD_NAME = "name"
const val EMERGENCY_TYPE = "emergencyType"
const val SEVERITY = "severity"
const val HANDLE_TIME = "handleTime"
const val MAX_DURATION = "maxDuration"

const val STAFF = "staff"
const val BASE_TYPE = "baseType"
const val LOCATION_VERTEX = "locationVertex"
const val DOCTORS = "doctors"
const val DOGS = "dogs"

const val EVENT_TYPE = "eventType"
const val DURATION = "duration"
const val ROAD_TYPES = "roadTypes"
const val FACTOR = "factor"
const val ONE_WAY_STREET = "oneWayStreet"
const val SOURCE = "source"
const val TARGET = "target"
const val VEHICLE_ID = "vehicleId"

const val ID = "id"
const val TICK = "tick"

const val LABEL_VILLAGE = "village"
const val LABEL_ROAD_NAME = "name"
const val JSON_LABEL_ROAD_NAME = "roadName"
const val LABEL_HEIGHT_LIMIT = "heightLimit"
const val LABEL_WEIGHT = "weight"
const val LABEL_PRIMARY_TYPE = "primaryType"
const val LABEL_SECONDARY_TYPE = "secondaryType"
const val LABEL_MAIN_STREET = "mainStreet"
const val LABEL_SIDE_STREET = "sideStreet"
const val LABEL_COUNTY_ROAD = "countyRoad"
const val LABEL_ONE_WAY_STREET = "oneWayStreet"
const val LABEL_EMERGENCY = "emergencyCalls"
const val LABEL_TUNNEL = "tunnel"
const val LABEL_NONE = "none"
