package de.unisaarland.cs.se.selab.model

enum class VehicleType {
    AMBULANCE, EMERGENCY_DOCTOR_CAR, FIRE_TRUCK_WATER, FIRE_TRUCK_TECHNICAL, FIRE_TRUCK_LADDER, FIREFIGHTER_TRANSPORTER, POLICE_CAR, K9_POLICE_CAR, POLICE_MOTOR_CYCLE
}
